apiVersion: v1
kind: ServiceAccount
metadata:
  name: ti-ops-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ti-ops-role
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["aquasecurity.github.io"]
  resources: ["vulnerabilityreports"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ti-ops-binding
subjects:
- kind: ServiceAccount
  name: ti-ops-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: ti-ops-role
  apiGroup: rbac.authorization.k8s.io
